/*
 * Copyright (c) 2026 Caleb L. Power
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.soulbind.sim;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * Picks the next action: seeded, weighted, and only from what is possible now.
 *
 * <p><b>Quasi-nondeterministic</b>, which is the methodology's word and the
 * right one. The sequence looks random and is entirely reproducible from a
 * seed — that is what makes a failing run something you can hand to somebody
 * else rather than a story about a thing that happened once.
 *
 * <p><b>Everything that must vary between runs is drawn OUTSIDE this stream.</b>
 * A run tag distinguishing this process's rows from an earlier run's is
 * generated by the caller and passed in; if it came from the seeded PRNG,
 * replaying a seed would either collide with the original run's data or shift
 * every subsequent draw. That is the single most common way a "reproducible"
 * generator turns out not to be, and it is why {@link #next} takes no source of
 * entropy but its own.
 *
 * <p>Only applicable actions are offered. Proposing a redeem when no code is
 * outstanding would spend a draw on something the executor must refuse, so the
 * weights would quietly stop meaning what they say — and the run would drift
 * toward whatever happens to be possible rather than toward what was chosen.
 */
public final class Generator {

    private final Random random;

    public Generator(long seed) {
        this.random = new Random(seed);
    }

    /**
     * Chooses the next action, or empty when nothing at all is possible.
     *
     * <p>Empty is a real answer and the caller must handle it rather than
     * looping: a world where no action applies is a world the run cannot
     * advance, and spinning on it would look like progress.
     */
    public java.util.Optional<Action> next(World world) {
        List<Action> candidates = applicable(world);
        if (candidates.isEmpty()) {
            return java.util.Optional.empty();
        }

        int total = 0;
        for (Action candidate : candidates) {
            total += candidate.kind().weight();
        }
        int roll = random.nextInt(total);
        for (Action candidate : candidates) {
            roll -= candidate.kind().weight();
            if (roll < 0) {
                return java.util.Optional.of(candidate);
            }
        }
        // Unreachable: the weights summed to `total` and the roll was below it.
        // Stated rather than assumed, because a silent fall-through here would
        // bias the tail of the distribution and nothing would ever say so.
        throw new IllegalStateException(
                "weighted choice fell through with " + candidates.size() + " candidates");
    }

    /**
     * Every action that could be taken right now, one per (kind, chosen target).
     *
     * <p>One candidate per kind, with its target already picked. Picking the
     * kind first and the target afterwards would take two draws where the
     * second is conditional on the first, and a replay would then depend on the
     * order the executor happened to evaluate them in.
     */
    private List<Action> applicable(World world) {
        List<Action> candidates = new ArrayList<>();
        List<Actor> actors = world.actors();
        if (actors.isEmpty()) {
            return candidates;
        }

        Actor actor = actors.get(random.nextInt(actors.size()));

        // Always available: an actor can ask for a code for an account it owns.
        if (!actor.identities().isEmpty()) {
            String ref = actor.identities().get(random.nextInt(actor.identities().size()));
            candidates.add(new Action(ActionKind.ISSUE_CODE, actor, ref, null));
            candidates.add(new Action(ActionKind.ABANDON_CODE, actor, ref, null));
            candidates.add(new Action(ActionKind.DESCRIBE, actor, ref, null));
        }

        Map<String, String> outstanding = world.outstandingCodes();
        if (!outstanding.isEmpty()) {
            List<String> codes = new ArrayList<>(outstanding.keySet());
            String code = codes.get(random.nextInt(codes.size()));
            String issuedFor = outstanding.get(code);
            // Redeemed by an identity that is NOT the one it was issued for --
            // redeeming your own code links an account to itself, which core
            // refuses and which would waste the draw.
            for (Actor other : actors) {
                for (String ref : other.identities()) {
                    if (!ref.equals(issuedFor)) {
                        candidates.add(new Action(ActionKind.REDEEM_CODE, other, code, ref));
                        break;
                    }
                }
                if (candidates.stream().anyMatch(c -> c.kind() == ActionKind.REDEEM_CODE)) {
                    break;
                }
            }
        }

        if (!world.gates().isEmpty()) {
            String gate = world.gates().get(random.nextInt(world.gates().size()));
            candidates.add(new Action(ActionKind.SET_RULE, actor, gate, null));
            candidates.add(new Action(ActionKind.CONFIG_FLIP, actor, gate, null));
            if (!actor.identities().isEmpty()) {
                String ref = actor.identities().get(0);
                candidates.add(new Action(ActionKind.DECIDE, actor, ref, gate));
            }
        }

        List<String> unlinked = world.unlinkedRefs();
        if (!unlinked.isEmpty()) {
            String ref = unlinked.get(random.nextInt(unlinked.size()));
            candidates.add(new Action(ActionKind.ACT_ON_UNLINKED, actor, ref, null));
        }

        List<Actor> stale = world.actorsWithAStaleCredential();
        if (!stale.isEmpty()) {
            Actor victim = stale.get(random.nextInt(stale.size()));
            candidates.add(new Action(ActionKind.STALE_CREDENTIAL, victim, null, null));
        }

        return candidates;
    }
}
