/*
 * Copyright (c) 2026 Caleb L. Power
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.soulbind.connector.plan;

import com.djrapitops.plan.extension.ExtensionService;
import com.google.inject.Inject;
import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.proxy.ProxyInitializeEvent;
import com.velocitypowered.api.plugin.Dependency;
import com.velocitypowered.api.plugin.Plugin;
import com.velocitypowered.api.plugin.annotation.DataDirectory;
import com.velocitypowered.api.proxy.Player;
import com.velocitypowered.api.proxy.ProxyServer;
import dev.soulbind.config.Config;
import dev.soulbind.sdk.DecisionCache;
import dev.soulbind.sdk.SoulbindClient;
import dev.soulbind.sdk.transport.Transport;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import org.slf4j.Logger;

/**
 * Registers the soulbind extension with a running Plan.
 *
 * <p>Wiring only. Everything that decides anything is in {@link LinkDataSource}
 * and {@link SoulbindDataExtension}, both testable in milliseconds without a
 * proxy, a Plan installation or a network — and this file is testable by none
 * of those means, which is exactly why it holds no judgement.
 *
 * <p><b>Velocity, not Paper.</b> §16 prefers it: Plan supports the platform and
 * Velocity's API module is MIT, where paper-api is GPLv3. Bootstrapping here
 * keeps this module distributable under Apache-2.0 without a departure.
 *
 * <p>That choice has a price, and it is not this file's to hide: <b>Plan on a
 * proxy supports MySQL only</b> — its own generated config says
 * "Supported databases: MySQL" — so a deployment running this connector needs a
 * MySQL-family server for Plan. Bootstrapping on Paper instead would let Plan
 * use SQLite, and would cost a GPLv3 compile dependency and a departure. §16
 * permits that only if paper-api becomes *unavoidable*, and it has not.
 *
 * <p>The Velocity plugin descriptor is hand-authored in
 * {@code src/main/resources/velocity-plugin.json} rather than generated by an
 * annotation processor, matching {@code connector-velocity}. Without it Velocity
 * refuses the jar outright with "Unable to load plugin" and the {@code @Plugin}
 * annotation above is decoration.
 *
 * <p><b>Why a separate plugin from the proxy connector.</b> They are separate
 * principals with separate credentials. This one is registered with
 * {@code code-display} — the least capability that reaches
 * {@code identity.describe} — so it cannot mutate the identity graph or change
 * policy, and the credential refuses it at core rather than this file
 * remembering to be careful. Sharing the proxy connector's plugin would mean
 * sharing its credential, and that one can enforce.
 *
 * <p>Not "inspection and nothing else", which is what this comment used to say:
 * soulbind has no read-only capability, so {@code code-display} is the floor and
 * it also permits minting a link code. {@code docs/DECISIONS.md} 8.14.
 */
@Plugin(
        id = "soulbind-plan",
        name = "soulbind-plan",
        version = "0.1.0",
        description = "Puts soulbind link state on Plan's pages",
        authors = {"Caleb L. Power"},
        // Declared, so Velocity loads this after Plan. Without it
        // ExtensionService.getInstance() races Plan's own startup and the
        // extension is silently absent -- a dashboard with a missing panel and
        // no error anywhere, which is this connector's whole failure mode.
        dependencies = {@Dependency(id = "plan")})
public final class SoulbindPlanPlugin {

    private final ProxyServer proxy;
    private final Logger logger;
    private final Path dataDirectory;

    private SoulbindDataExtension extension;

    @Inject
    public SoulbindPlanPlugin(
            ProxyServer proxy, Logger logger, @DataDirectory Path dataDirectory) {
        this.proxy = proxy;
        this.logger = logger;
        this.dataDirectory = dataDirectory;
    }

    @Subscribe
    public void onInitialize(ProxyInitializeEvent event) {
        Path configFile = dataDirectory.resolve("soulbind-plan.toml");
        if (!Files.isRegularFile(configFile)) {
            // Refuse to run half-configured, the same way the proxy connector
            // does. A dashboard that starts with defaults and shows nothing
            // looks exactly like a dashboard whose players have not linked.
            logger.error(
                    "no configuration at {}. soulbind link state will not appear on Plan's "
                            + "pages until it exists -- see the module README.",
                    configFile);
            return;
        }

        Config config;
        try {
            config = PlanConfig.load(configFile);
        } catch (RuntimeException e) {
            logger.error("configuration could not be read: {}", e.getMessage());
            return;
        }

        var problems = PlanConfig.validate(config);
        if (!problems.isEmpty()) {
            problems.forEach(logger::error);
            return;
        }

        Transport transport = new dev.soulbind.sdk.transport.HttpTransport(
                config.getString(PlanConfig.CORE_URL),
                config.findString(PlanConfig.CREDENTIAL).orElse(""),
                Clock.systemUTC());

        SoulbindClient client = new SoulbindClient(
                transport,
                config.findString(PlanConfig.CREDENTIAL).orElse(""),
                Clock.systemUTC(),
                new DecisionCache());

        LinkDataSource data = new LinkDataSource(
                client,
                PlanConfig.platformKind(config),
                PlanConfig.cacheTtl(config),
                PlanConfig.showSubjectId(config),
                Clock.systemUTC());

        extension = new SoulbindDataExtension(data, this::roster);

        try {
            ExtensionService.getInstance()
                    .register(extension)
                    .ifPresentOrElse(
                            caller -> logger.info(
                                    "registered with Plan; link state will appear on player and "
                                            + "server pages"),
                            () -> logger.error(
                                    "Plan accepted no extension. Its pages will show no soulbind "
                                            + "data, and Plan itself will report nothing wrong."));
        } catch (IllegalStateException e) {
            // Thrown when Plan is not enabled. Reported rather than swallowed:
            // the symptom otherwise is a page that renders perfectly with one
            // section absent, which nobody reads as a failure.
            logger.error(
                    "Plan is not available, so nothing was registered: {}", e.getMessage());
        }
    }

    /**
     * Who to report on: the players currently connected to this proxy.
     *
     * <p>Plan asks about the players it knows; core does not know who is online
     * and should not be asked to guess. Read fresh on every call rather than
     * cached, because the roster is the one input that changes by the second and
     * {@link LinkDataSource} already caches the answers about it.
     */
    private Map<UUID, String> roster() {
        Map<UUID, String> players = new LinkedHashMap<>();
        for (Player player : proxy.getAllPlayers()) {
            players.put(player.getUniqueId(), player.getUsername());
        }
        return players;
    }
}
