/*
 * Copyright (c) 2026 Caleb L. Power
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.soulbind.guards;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Every module that ships Java generates a licence inventory.
 *
 * <p>The inventory itself is generated by a Gradle task that fails the build on
 * an unknown licence, an undeclared one, or a copyleft artifact that would be
 * bundled. That task is only as good as the set of modules it runs over — and a
 * module created later that nobody remembers to wire up is outside it entirely,
 * with every other check still green. That is the same shape as the failure
 * `NOTICE` spent eight phases in (docs/DECISIONS.md 10.1): a claim about the
 * project that nothing read.
 *
 * <p>So the coverage is derived from {@code settings.gradle.kts} rather than
 * hand-listed here. A new module is inventoried by default and has to be
 * excluded deliberately, with a reason, rather than by omission.
 */
class LicenceInventoryGuardTest {

    /**
     * {@code guards} and {@code sim} ship nowhere.
     *
     * <p>Exactly the exclusion {@link ReleaseLevelGuardTest} uses and for the
     * same reason: {@code guards} reads the repository as data and {@code sim}
     * drives it as a client. Neither is a distributed artifact, so neither has
     * third-party obligations to disclose. Every other module is covered — this
     * list is not a place to put a module that was inconvenient to wire up.
     */
    private static final Set<String> NOT_DISTRIBUTED = Set.of("guards", "sim");

    private static final String PLUGIN = "soulbind.licence-inventory";

    @Test
    @DisplayName("every distributed module applies the licence inventory plugin")
    void everyDistributedModuleIsInventoried() throws IOException {
        List<String> missing = new ArrayList<>();
        int checked = 0;

        for (String module : SourceTree.allModules()) {
            if (NOT_DISTRIBUTED.contains(module)) {
                continue;
            }
            Path buildFile = SourceTree.repoRoot().resolve(module).resolve("build.gradle.kts");
            if (!Files.isRegularFile(buildFile)) {
                buildFile = SourceTree.repoRoot()
                        .resolve("harness").resolve(module).resolve("build.gradle.kts");
            }
            if (!Files.isRegularFile(buildFile)) {
                fail("module '" + module + "' is in settings.gradle.kts but has no"
                        + " build.gradle.kts anywhere this guard looks");
            }
            checked++;
            if (!Files.readString(buildFile).contains(PLUGIN)) {
                missing.add(module);
            }
        }

        // A run that checked nothing passes the assertion below.
        assertTrue(checked > 0, "no modules were checked, so this guard asserted nothing");

        assertTrue(missing.isEmpty(),
                "these modules ship Java and do not generate a licence inventory: " + missing
                        + ". Add id(\"" + PLUGIN + "\") to the module's plugins block, or"
                        + " add it to NOT_DISTRIBUTED here with the reason it ships nowhere."
                        + " A distributed artifact without an inventory is an undisclosed"
                        + " third-party graph.");
    }

    @Test
    @DisplayName("the rules file states a handling for every licence it allows")
    void everyAllowedLicenceStatesItsHandling() throws IOException {
        // "May this be shaded?" is the question §16 turns on. The generator
        // reads the handling from this file rather than inferring it from the
        // licence name, so an entry without one would be a licence whose
        // packaging rule nobody stated.
        Path rules = SourceTree.repoRoot().resolve("gradle/licences.conf");
        assertTrue(Files.isRegularFile(rules), "gradle/licences.conf is missing");

        List<String> bad = new ArrayList<>();
        int allowed = 0;
        String section = "";
        for (String raw : Files.readAllLines(rules)) {
            String line = raw.contains("#") ? raw.substring(0, raw.indexOf('#')).trim() : raw.trim();
            if (line.isEmpty()) {
                continue;
            }
            if (line.startsWith("[") && line.endsWith("]")) {
                section = line.substring(1, line.length() - 1);
                continue;
            }
            if (!section.equals("allowed")) {
                continue;
            }
            allowed++;
            String value = line.substring(line.indexOf('=') + 1).trim();
            String handling = value.contains("|")
                    ? value.substring(0, value.indexOf('|')).trim()
                    : "";
            if (!Set.of("shadeable", "unbundled", "not-distributed").contains(handling)) {
                bad.add(line);
            }
        }

        assertTrue(allowed > 0, "the [allowed] section is empty, so this guard asserted nothing");
        assertTrue(bad.isEmpty(),
                "these allowlisted licences state no packaging handling: " + bad
                        + ". Each must be shadeable, unbundled or not-distributed.");
    }

    @Test
    @DisplayName("NOTICE does not go back to claiming a hand-maintained complete list")
    void noticePointsAtTheGenerator() throws IOException {
        // The inverse of NoticeGuardTest's assertion, which stops NOTICE
        // claiming a generator that does not exist. One exists now, and the
        // failure available from here is the opposite: the inline list quietly
        // being presented as complete again while the graph grows past it.
        String notice = Files.readString(SourceTree.repoRoot().resolve("NOTICE"));

        assertTrue(notice.contains("THIRD-PARTY.txt"),
                "NOTICE does not name the generated inventory that ships beside it,"
                        + " so a redistributor reading only NOTICE would take its inline"
                        + " list for the whole graph. It is not: the list is the declared"
                        + " dependencies and the graph is around forty artifacts.");
        assertFalse(notice.contains("is generated at build time and ships in every"),
                "NOTICE has the pre-Phase-10 sentence back. See docs/DECISIONS.md 10.1.");
    }
}
